name: caddy
base: core18
version: "1.0.0"
summary: Caddy web server
description: etc
grade: stable
confinement: strict

apps:
  caddy:
    command: run
    daemon: simple
    restart-condition: on-abnormal
    plugs: [network-bind]
  validate:
    command: caddy -validate -conf stdin

parts:
  caddy:
    build-snaps:
      - go
    plugin: nil
    source: .
    override-build: |
      env GOBIN=$SNAPCRAFT_PART_INSTALL/bin GOPROXY=https://proxy.golang.org go install
  run:
    plugin: dump
    source: bin
    organize:
      run: bin/run
