name: caddy
version: "0.11.0"
summary: Caddy web server
description: etc
grade: stable
confinement: strict

apps:
  caddy:
    command: run
    daemon: simple
    restart-condition: on-abnormal
    plugs: [network-bind, home]       
  check:
    command: caddy -validate -conf stdin

plugs:
  home:
    read: all
         
parts:
  caddy:
    plugin: dump
    source:
      - on i386:  https://caddyserver.com/download/linux/386?plugins=tls.dns.cloudflare&license=personal&telemetry=off
      - on amd64: https://caddyserver.com/download/linux/amd64?plugins=tls.dns.cloudflare&license=personal&telemetry=off
      - on armhf: https://caddyserver.com/download/linux/arm7?plugins=tls.dns.cloudflare&license=personal&telemetry=off
      - on arm64: https://caddyserver.com/download/linux/arm64?plugins=tls.dns.cloudflare&license=personal&telemetry=off
    source-type: tar
    organize:
      caddy: bin/caddy
    stage:
      - bin/caddy
  run:
    plugin: dump
    source: bin
    organize:
      run: bin/run
      