name: caddy
version: "0.11.0"
summary: Caddy web server
description: etc
grade: stable
confinement: strict

apps:
  caddy:
    command: run
    daemon: simple
    restart-condition: on-abnormal
    plugs: [network-bind, home]       
  check:
    command: caddy -validate -conf stdin

plugs:
  home:
    read: all
         
parts:
  caddy:
    plugin: nil
    build-packages:
    - curl
    source: .
    override-build: |
      export ANDROID_ROOT=FAKE
      export PREFIX=$SNAPCRAFT_PART_INSTALL
      mkdir -p $PREFIX/bin
      mkdir -p $PREFIX/tmp
      cat getcaddy.bash | bash -s personal tls.dns.cloudflare
    stage:
      - bin/caddy
  run:
    plugin: dump
    source: bin
    organize:
      run: bin/run
      