name: caddy
summary: Fast, multi-platform web server with automatic HTTPS.
description: |
  Caddy is a powerful, extensible platform to serve your sites, services, and
  apps, written in Go.
version: "v2.0.0-rc.3"

base: core18
grade: devel
confinement: strict
epoch: 2

apps:
  caddy:
    command: caddy.sh
    plugs:
      - home
      - network-bind
  deamon:
    command: daemon.sh
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network-bind

parts:
  caddy:
    build-packages:
      - build-essential
    build-snaps:
      - go
    plugin: nil
    override-build: |
      set -e
      go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      $(go env GOPATH)/bin/xcaddy build --output $SNAPCRAFT_PART_INSTALL/bin/caddy
  launcher:
    plugin: dump
    source: snap/local/
    organize:
      "*": bin/
