name: caddy
base: core18
version: "1.0.0"
summary: Caddy web server
description: |
  Caddy is an open source, HTTP/2-enabled web server written in Go.
  One of Caddy's most notable features is enabling HTTPS by default.
grade: stable
confinement: strict

apps:
  caddy:
    command: caddy.sh
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network-bind
  validate:
    command: caddy -validate -conf stdin

parts:
  caddy:
    build-snaps:
      - go
    plugin: nil
    source: .
    build-environment:
      - GO111MODULE: "on"
      - GOPROXY: https://proxy.golang.org
    override-build: |
      env GOBIN=$SNAPCRAFT_PART_INSTALL/bin go install
  launcher:
    plugin: dump
    source: snap/local/
    organize:
      "*": bin/
